[profile.default]
optimizer_runs = 1000000
remappings = [
    "@clones/=lib/clones-with-immutable-args/src/",
    "create3-factory/=lib/create3-factory/src/",
]
verbosity = 1

# Extreme Fuzzing CI Profile :P
[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
goerli = "${RPC_URL_GOERLI}"
mainnet = "${RPC_URL_MAINNET}"
sepolia = "https://sepolia.rpc.zora.energy/"
zora = "https://rpc.zora.energy/"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api" }
zora = { key = "some", url = "https://explorer.zora.energy/api" }
sepolia = { key = "key", url = "https://sepolia.zora.energy/api" }
mainnet = { key = "${ETHERSCAN_KEY}" }
